const labels = {
  active: 'Активно',
  all: 'Все',
  analytics: 'Аналитика',
  autotech: 'Автобизнес',
  autotech_niches: 'Ниши автобизнеса',
  bank_transfer: 'Банк',
  bug: 'Ошибка',
  business: 'Бизнес',
  call: 'Звонок',
  cancelled: 'Отменено',
  car_wash: 'Автомойка',
  cash: 'Наличные',
  check_contact: 'Проверить контакт',
  client: 'Клиент',
  clients: 'Клиенты',
  closed: 'Закрыто',
  configuration: 'Настройка',
  consultation: 'Консультация',
  contact_check: 'Проверка контакта',
  content: 'Контент',
  communication_results: 'Результаты общения',
  dashboard: 'Рабочий стол',
  data_collection: 'Сбор данных',
  debt: 'Долг',
  debt_created: 'Создан долг',
  debt_paid: 'Долг закрыт',
  debt_statuses: 'Статусы долгов',
  deal_stages: 'Этапы сделок',
  developer: 'Программист',
  diagnostics: 'Диагностика',
  diagnostics_created: 'Диагностика создана',
  done: 'Готово',
  due_soon: 'Скоро оплата',
  edutech: 'Обучение',
  edutech_niches: 'Ниши обучения',
  expensive: 'Дорого',
  finance: 'Финансы',
  first_message: 'Первое сообщение',
  first_touch: 'Первое касание',
  follow_up: 'Повторный контакт',
  general: 'Общее',
  high: 'Высокий',
  implementation: 'Внедрение',
  implementation_checklist_item_updated: 'Пункт внедрения обновлен',
  implementation_launched: 'Запуск передан в поддержку',
  implementation_project: 'Внедрение',
  implementation_status_changed: 'Статус внедрения изменен',
  implementation_statuses: 'Статусы внедрения',
  in_progress: 'В работе',
  inactive: 'Отключено',
  interested: 'Интерес есть',
  kaspi: 'Kaspi',
  kids_center: 'Детский центр',
  language_school: 'Языковая школа',
  launch: 'Запуск',
  lead: 'Заявка',
  lead_created: 'Заявка создана',
  lead_updated: 'Заявка обновлена',
  lead_statuses: 'Статусы заявок',
  leads: 'Заявки',
  lost: 'Проиграно',
  low: 'Низкий',
  manager: 'Менеджер',
  materials: 'Материалы',
  meeting: 'Встреча',
  meeting_set: 'Встреча назначена',
  medium: 'Средний',
  mixed_education: 'Смешанный учебный центр',
  mixed_service: 'Смешанный автосервис',
  music_school: 'Музыкальная школа',
  network: 'Сеть',
  new: 'Новая',
  no_answer: 'Нет ответа',
  note_created: 'Заметка добавлена',
  oil_change: 'Пункт замены масла',
  open: 'Открыто',
  overdue: 'Просрочено',
  owner: 'Владелец',
  packages: 'Пакеты',
  paid: 'Оплачено',
  paid_change: 'Платная доработка',
  paused: 'Пауза',
  payment: 'Оплата',
  payment_recorded: 'Оплата записана',
  pending: 'Ожидает оплаты',
  prepare_proposal: 'Подготовить предложение',
  presentation: 'Презентация',
  pro: 'Про',
  proposal: 'Предложение',
  proposal_created: 'Предложение создано',
  proposal_sent: 'Предложение отправлено',
  question: 'Вопрос',
  ready_to_launch: 'Готово к запуску',
  reference_item: 'Справочник',
  reference_item_created: 'Элемент справочника создан',
  reference_item_updated: 'Элемент справочника обновлен',
  rejected: 'Отказ',
  repair_shop: 'СТО',
  return_later: 'Вернуться позже',
  roles: 'Роли',
  sales_lead: 'Руководитель продаж',
  settings: 'Настройки',
  start: 'Старт',
  subscription_created: 'Подписка создана',
  subscription_renewed: 'Подписка продлена',
  subscription_statuses: 'Статусы подписок',
  supervisor: 'Управляющий',
  support: 'Поддержка',
  support_ticket: 'Обращение',
  support_ticket_assigned: 'Обращение назначено',
  support_ticket_closed: 'Обращение закрыто',
  support_ticket_created: 'Обращение создано',
  support_ticket_updated: 'Обращение обновлено',
  support_ticket_statuses: 'Статусы обращений',
  support_ticket_types: 'Типы обращений',
  system: 'Системное',
  task_created: 'Задача создана',
  task: 'Задача',
  task_assigned: 'Задача назначена',
  task_completed: 'Задача завершена',
  task_rescheduled: 'Задача перенесена',
  task_types: 'Типы задач',
  team: 'Команда',
  testing: 'Тестирование',
  tire_service: 'Шиномонтаж',
  trial_support: 'Бесплатная поддержка',
  tutoring_center: 'Репетиторский центр',
  waiting_client: 'Ждем клиента',
  waiting_start: 'Ожидает старта',
  won: 'Выиграно',
};

export function labelValue(value) {
  const key = String(value || '').trim();
  if (!key) return '';
  return labels[key] || key
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export function directionLabel(value) {
  return labelValue(value);
}
